# Generated by Django 2.2.6 on 2021-03-27 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_posts',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 0, 23, 1, 144718), verbose_name='date published'),
        ),
    ]
